export enum ErrorCodes {
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  RATE_LIMITED = 'RATE_LIMITED',
  VALIDATION_ERROR = 'VALIDATION_ERROR',

  // Auth related
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  SESSION_REQUIRED = 'SESSION_REQUIRED',
  SESSION_INVALID = 'SESSION_INVALID',
  CSRF_INVALID = 'CSRF_INVALID',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',

  // User related
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_EXISTS = 'USER_EXISTS',
  EMAIL_EXISTS = 'EMAIL_EXISTS',
  USERNAME_EXISTS = 'USERNAME_EXISTS',

  // Passkeys related
  PASSKEY_NOT_FOUND = 'PASSKEY_NOT_FOUND',
  PASSKEY_REGISTRATION_FAILED = 'PASSKEY_REGISTRATION_FAILED',
  PASSKEY_AUTHENTICATION_FAILED = 'PASSKEY_AUTHENTICATION_FAILED',
  CHALLENGE_EXPIRED = 'CHALLENGE_EXPIRED',
  CHALLENGE_NOT_FOUND = 'CHALLENGE_NOT_FOUND',

  // Projects related
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',
  PROJECT_FORBIDDEN = 'PROJECT_FORBIDDEN',
}